feat: enhance release workflow with version input and artifact handling

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,17 +1,34 @@
 name: Release
 
 on:
-  push:
-    tags:
-      - v*
+  workflow_dispatch:
+    inputs:
+      version:
+        description: "The new version number (e.g., 1.1)"
+        required: true
+      changelog:
+        description: "The changelog for this version"
+        required: true
 
 env:
   FORCE_COLOR: true
 
 jobs:
+  create-tag:
+    runs-on: ubuntu-22.04
+    steps:
+    - name: Checkout Repository
+      uses: actions/checkout@v4
+    - name: Create Git Tag
+      run: |
+        git config user.name "github-actions[bot]"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        git tag "v${{ github.event.inputs.version }}" || echo "Tag creation failed (possibly already exists)."
+        git push origin "v${{ github.event.inputs.version }}" || echo "Tag push failed (possibly already exists)."
 
   build_windows:
     runs-on: windows-latest
+    needs: create-tag
     strategy:
       matrix:
         build_type: [Release, Debug]
@@ -21,16 +38,7 @@ jobs:
 
     - name: Set Release variable
       run: |
-        $env:Release = '${{ matrix.build_type }}'
-
-    - name: Install sccache
-      run: choco install sccache -y
-
-    - name: Configure sccache
-      run: |
-        set SCCACHE_DIR=D:\a\StreamLabsTikTokStreamKeyGenerator\StreamLabsTikTokStreamKeyGenerator\.sccache
-        set SCCACHE_CACHE_SIZE=500M
-        set RUSTC_WRAPPER=sccache
+        echo "RELEASE=${{ matrix.build_type }}" >> $env:GITHUB_ENV
 
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
@@ -40,28 +48,63 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install Nuitka
+        pip install Nuitka clang
         if (Test-Path requirements.txt) {
           pip install -r requirements.txt
         }
 
     - name: Build Executable
       run: |
+        Write-Host "Release variable is set to: $env:Release"
         if ($env:Release -eq 'Release') {
-          sccache --show-stats
-          nuitka --windows-console-mode=disable --msvc=latest --assume-yes-for-downloads --onefile --follow-imports --enable-plugin=tk-inter --include-data-file=.seleniumwire/seleniumwire-ca.pem=seleniumwire/.seleniumwire/seleniumwire-ca.pem --include-data-file=.seleniumwire/seleniumwire-dhparam.pem=seleniumwire/.seleniumwire/seleniumwire-dhparam.pem StreamLabsTikTokStreamKeyGenerator.py
-          sccache --show-stats
+          nuitka `
+          --assume-yes-for-downloads `
+          --show-scons `
+          --clang `
+          --lto=no `
+          --jobs=4 `
+          --static-libpython=no `
+          --standalone `
+          --enable-plugin=anti-bloat `
+          --enable-plugin=tk-inter `
+          --show-modules `
+          --show-anti-bloat-changes `
+          --follow-stdlib `
+          --follow-imports `
+          --nofollow-import-to="*.tests" `
+          --nofollow-import-to="unittest" `
+          --nofollow-import-to="pydoc" `
+          --nofollow-import-to="test" `
+          --prefer-source-code `
+          --windows-console-mode=disable `
+          --include-data-dir=".seleniumwire=.seleniumwire" `
+          StreamLabsTikTokStreamKeyGenerator.py
         } else {
-          sccache --show-stats
-          nuitka --msvc=latest --assume-yes-for-downloads --onefile --follow-imports --enable-plugin=tk-inter --include-data-file=.seleniumwire/seleniumwire-ca.pem=seleniumwire/.seleniumwire/seleniumwire-ca.pem --include-data-file=.seleniumwire/seleniumwire-dhparam.pem=seleniumwire/.seleniumwire/seleniumwire-dhparam.pem StreamLabsTikTokStreamKeyGenerator.py
-          sccache --show-stats
+          nuitka `
+          --assume-yes-for-downloads `
+          --show-scons `
+          --clang `
+          --lto=no `
+          --jobs=4 `
+          --static-libpython=no `
+          --standalone `
+          --enable-plugin=anti-bloat `
+          --enable-plugin=tk-inter `
+          --show-modules `
+          --show-anti-bloat-changes `
+          --follow-stdlib `
+          --follow-imports `
+          --nofollow-import-to="*.tests" `
+          --nofollow-import-to="unittest" `
+          --nofollow-import-to="pydoc" `
+          --nofollow-import-to="test" `
+          --prefer-source-code `
+          --include-data-dir=".seleniumwire=.seleniumwire" `
+          StreamLabsTikTokStreamKeyGenerator.py
         }
 
-    - name: Rename Executable
-      run: Rename-Item -Path StreamLabsTikTokStreamKeyGenerator.exe -NewName StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-win.exe
-
     - name: Compress Executable
-      run: Compress-Archive -Path StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-win.exe -DestinationPath StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-win.zip
+      run: Compress-Archive -Path StreamLabsTikTokStreamKeyGenerator.dist\* -DestinationPath StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-win.zip
 
     - name: Upload artifacts
       uses: actions/upload-artifact@v4
@@ -72,18 +115,14 @@ jobs:
 
   build_macos:
     runs-on: macos-latest
+    needs: create-tag
     strategy:
       matrix:
         architecture: [x86_64, arm64]
-        build_type: [Release, Debug]
+        build_type: [Release]
 
     steps:
     - uses: actions/checkout@v3
-
-    - name: Set up ccache
-      uses: hendrikmuhs/ccache-action@v1.2.14
-      with:
-        create-symlink: true
 
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
@@ -93,85 +132,100 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install Nuitka
+        pip install Nuitka clang
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
     - name: Build Executable
       run: |
-        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
-        arch -${{ matrix.architecture }} nuitka --windows-console-mode=disable --assume-yes-for-downloads --standalone --macos-create-app-bundle --macos-target-arch=${{ matrix.architecture }} --onefile --follow-imports --enable-plugin=tk-inter --include-data-file=.seleniumwire/seleniumwire-ca.pem=seleniumwire/.seleniumwire/seleniumwire-ca.pem --include-data-file=.seleniumwire/seleniumwire-dhparam.pem=seleniumwire/.seleniumwire/seleniumwire-dhparam.pem StreamLabsTikTokStreamKeyGenerator.py
-
-    - name: Remove quarantine attribute
-      run: xattr -dr com.apple.quarantine StreamLabsTikTokStreamKeyGenerator.app
-
-    - name: Rename Executable
-      run: mv StreamLabsTikTokStreamKeyGenerator.app StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-${{ matrix.architecture }}-macos.app
+        arch -${{ matrix.architecture }} nuitka \
+        --assume-yes-for-downloads \
+        --show-scons \
+        --clang \
+        --lto=no \
+        --jobs=4 \
+        --static-libpython=no \
+        --standalone \
+        --enable-plugin=anti-bloat \
+        --show-modules \
+        --show-anti-bloat-changes \
+        --follow-stdlib \
+        --follow-imports \
+        --nofollow-import-to="*.tests" \
+        --nofollow-import-to="unittest" \
+        --nofollow-import-to="pydoc" \
+        --nofollow-import-to="test" \
+        --prefer-source-code \
+        --include-data-dir=".seleniumwire=.seleniumwire" \
+        --macos-target-arch=${{ matrix.architecture }} \
+        StreamLabsTikTokStreamKeyGenerator.py
 
     - name: Compress Executable
-      run: zip -r StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-${{ matrix.architecture }}-macos.zip StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-${{ matrix.architecture }}-macos.app
+      run: |
+        zip -r StreamLabsTikTokStreamKeyGenerator-${{ matrix.architecture }}-macos.zip StreamLabsTikTokStreamKeyGenerator.dist/*
 
-    - name: Upload architecture-specific artifacts
+    - name: Upload artifacts
       uses: actions/upload-artifact@v4
       with:
-        name: macos-${{ matrix.build_type }}-${{ matrix.architecture }}
-        path: StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-${{ matrix.architecture }}-macos.zip
+        name: macos-${{ matrix.architecture }}
+        path: |
+          StreamLabsTikTokStreamKeyGenerator-${{ matrix.architecture }}-macos.zip
 
   build_linux:
     runs-on: ubuntu-latest
+    needs: create-tag
     strategy:
       matrix:
-        build_type: [Release, Debug]
+        build_type: [Release]
 
     steps:
     - uses: actions/checkout@v3
 
-    - name: Set Release variable
-      run: echo "Release=${{ matrix.build_type }}" >> $GITHUB_ENV
 
     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y ccache python3-pip python3-tk zip
         python3 -m pip install --upgrade pip
-        pip3 install Nuitka
+        pip3 install Nuitka clang
         if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
-
-    - name: Configure ccache
-      run: |
-        export CCACHE_DIR=$HOME/.cache/ccache
-        export CC="ccache gcc"
-        export CXX="ccache g++"
-        export CCACHE_MAXSIZE="500M"
-        ccache --zero-stats
 
     - name: Build Executable
       run: |
-        if [ "$Release" == "Release" ]; then
-          ccache --show-stats
-          nuitka --standalone --onefile --follow-imports --enable-plugin=tk-inter --include-data-dir=.seleniumwire=seleniumwire StreamLabsTikTokStreamKeyGenerator.py
-          ccache --show-stats
-        else
-          ccache --show-stats
-          nuitka --standalone --onefile --follow-imports --enable-plugin=tk-inter --include-data-dir=.seleniumwire=seleniumwire StreamLabsTikTokStreamKeyGenerator.py
-          ccache --show-stats
-        fi
+          nuitka \
+          --assume-yes-for-downloads \
+          --show-scons \
+          --clang \
+          --lto=no \
+          --jobs=4 \
+          --static-libpython=no \
+          --standalone \
+          --enable-plugin=anti-bloat \
+          --show-modules \
+          --show-anti-bloat-changes \
+          --follow-stdlib \
+          --follow-imports \
+          --nofollow-import-to="*.tests" \
+          --nofollow-import-to="unittest" \
+          --nofollow-import-to="pydoc" \
+          --nofollow-import-to="test" \
+          --prefer-source-code \
+          --include-data-dir=".seleniumwire=.seleniumwire" \
+          StreamLabsTikTokStreamKeyGenerator.py
 
-    - name: Rename Executable
-      run: mv StreamLabsTikTokStreamKeyGenerator.bin StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-linux.bin
 
     - name: Compress Executable
-      run: zip StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-linux.zip StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-linux.bin
+      run: zip -r StreamLabsTikTokStreamKeyGenerator-linux.zip StreamLabsTikTokStreamKeyGenerator.dist/*
 
     - name: Upload artifacts
       uses: actions/upload-artifact@v4
       with:
-        name: linux-${{ matrix.build_type }}
+        name: linux-
         path: |
-          ./StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-linux.zip
+          ./StreamLabsTikTokStreamKeyGenerator-linux.zip
 
   release:
     runs-on: ubuntu-latest
-    needs: [build_windows, build_macos, build_linux]
+    needs: [build_linux, build_windows, build_macos]
 
     steps:
       - name: Checkout code
@@ -203,15 +257,12 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          name: ${{ github.ref_name }}
-          prerelease: ${{ github.event.inputs.prerelease }}
-          draft: false
+          tag_name: "v${{ github.event.inputs.version }}"
+          body: ${{ github.event.inputs.changelog }}
           files: |
             ./windows/StreamLabsTikTokStreamKeyGeneratorRelease-win.zip
             ./windows/StreamLabsTikTokStreamKeyGeneratorDebug-win.zip
-            ./macos/StreamLabsTikTokStreamKeyGeneratorRelease-x86_64-macos.zip
-            ./macos/StreamLabsTikTokStreamKeyGeneratorDebug-x86_64-macos.zip
-            ./macos/StreamLabsTikTokStreamKeyGeneratorRelease-arm64-macos.zip
-            ./macos/StreamLabsTikTokStreamKeyGeneratorDebug-arm64-macos.zip
-            ./linux/StreamLabsTikTokStreamKeyGeneratorRelease-linux.zip
-            ./linux/StreamLabsTikTokStreamKeyGeneratorDebug-linux.zip
+            ./macos/StreamLabsTikTokStreamKeyGenerator-x86_64-macos.zip
+            ./macos/StreamLabsTikTokStreamKeyGenerator-arm64-macos.zip
+            ./linux/StreamLabsTikTokStreamKeyGenerator-linux.zip
+  
