feat: add CA certificate and private key for Selenium Wire

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,14 +17,14 @@ jobs:
   create-tag:
     runs-on: ubuntu-22.04
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v4
-    - name: Create Git Tag
-      run: |
-        git config user.name "github-actions[bot]"
-        git config user.email "github-actions[bot]@users.noreply.github.com"
-        git tag "v${{ github.event.inputs.version }}" || echo "Tag creation failed (possibly already exists)."
-        git push origin "v${{ github.event.inputs.version }}" || echo "Tag push failed (possibly already exists)."
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+      - name: Create Git Tag
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git tag "v${{ github.event.inputs.version }}" || echo "Tag creation failed (possibly already exists)."
+          git push origin "v${{ github.event.inputs.version }}" || echo "Tag push failed (possibly already exists)."
 
   build_windows:
     runs-on: windows-latest
@@ -34,84 +34,86 @@ jobs:
         build_type: [Release, Debug]
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set Release variable
-      run: |
-        echo "RELEASE=${{ matrix.build_type }}" >> $env:GITHUB_ENV
+      - name: Set Release variable
+        run: |
+          echo "RELEASE=${{ matrix.build_type }}" >> $env:GITHUB_ENV
 
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.10"
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.10"
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install Nuitka clang
-        if (Test-Path requirements.txt) {
-          pip install -r requirements.txt
-        }
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install Nuitka clang
+          if (Test-Path requirements.txt) {
+            pip install -r requirements.txt
+          }
 
-    - name: Build Executable
-      run: |
-        Write-Host "Release variable is set to: $env:Release"
-        if ($env:Release -eq 'Release') {
-          nuitka `
-          --assume-yes-for-downloads `
-          --show-scons `
-          --clang `
-          --lto=no `
-          --jobs=4 `
-          --static-libpython=no `
-          --standalone `
-          --enable-plugin=anti-bloat `
-          --enable-plugin=tk-inter `
-          --show-modules `
-          --show-anti-bloat-changes `
-          --follow-stdlib `
-          --follow-imports `
-          --nofollow-import-to="*.tests" `
-          --nofollow-import-to="unittest" `
-          --nofollow-import-to="pydoc" `
-          --nofollow-import-to="test" `
-          --prefer-source-code `
-          --windows-console-mode=disable `
-          --include-data-dir=".seleniumwire=.seleniumwire" `
-          StreamLabsTikTokStreamKeyGenerator.py
-        } else {
-          nuitka `
-          --assume-yes-for-downloads `
-          --show-scons `
-          --clang `
-          --lto=no `
-          --jobs=4 `
-          --static-libpython=no `
-          --standalone `
-          --enable-plugin=anti-bloat `
-          --enable-plugin=tk-inter `
-          --show-modules `
-          --show-anti-bloat-changes `
-          --follow-stdlib `
-          --follow-imports `
-          --nofollow-import-to="*.tests" `
-          --nofollow-import-to="unittest" `
-          --nofollow-import-to="pydoc" `
-          --nofollow-import-to="test" `
-          --prefer-source-code `
-          --include-data-dir=".seleniumwire=.seleniumwire" `
-          StreamLabsTikTokStreamKeyGenerator.py
-        }
+      - name: Build Executable
+        run: |
+          Write-Host "Release variable is set to: $env:Release"
+          if ($env:Release -eq 'Release') {
+            nuitka `
+            --assume-yes-for-downloads `
+            --show-scons `
+            --clang `
+            --lto=no `
+            --jobs=4 `
+            --static-libpython=no `
+            --standalone `
+            --enable-plugin=anti-bloat `
+            --enable-plugin=tk-inter `
+            --show-modules `
+            --show-anti-bloat-changes `
+            --follow-stdlib `
+            --follow-imports `
+            --nofollow-import-to="*.tests" `
+            --nofollow-import-to="unittest" `
+            --nofollow-import-to="pydoc" `
+            --nofollow-import-to="test" `
+            --prefer-source-code `
+            --windows-console-mode=disable `
+            --include-data-dir=".seleniumwire=.seleniumwire" `
+            --include-data-dir="seleniumwire=seleniumwire" `
+            StreamLabsTikTokStreamKeyGenerator.py
+          } else {
+            nuitka `
+            --assume-yes-for-downloads `
+            --show-scons `
+            --clang `
+            --lto=no `
+            --jobs=4 `
+            --static-libpython=no `
+            --standalone `
+            --enable-plugin=anti-bloat `
+            --enable-plugin=tk-inter `
+            --show-modules `
+            --show-anti-bloat-changes `
+            --follow-stdlib `
+            --follow-imports `
+            --nofollow-import-to="*.tests" `
+            --nofollow-import-to="unittest" `
+            --nofollow-import-to="pydoc" `
+            --nofollow-import-to="test" `
+            --prefer-source-code `
+            --include-data-dir=".seleniumwire=.seleniumwire" `
+            --include-data-dir="seleniumwire=seleniumwire" `
+            StreamLabsTikTokStreamKeyGenerator.py
+          }
 
-    - name: Compress Executable
-      run: Compress-Archive -Path StreamLabsTikTokStreamKeyGenerator.dist\* -DestinationPath StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-win.zip
+      - name: Compress Executable
+        run: Compress-Archive -Path StreamLabsTikTokStreamKeyGenerator.dist\* -DestinationPath StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-win.zip
 
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: windows-${{ matrix.build_type }}
-        path: |
-          ./StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-win.zip
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: windows-${{ matrix.build_type }}
+          path: |
+            ./StreamLabsTikTokStreamKeyGenerator${{ matrix.build_type }}-win.zip
 
   build_macos:
     runs-on: macos-latest
@@ -122,55 +124,56 @@ jobs:
         build_type: [Release]
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.10"
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.10"
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install Nuitka clang
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install Nuitka clang
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
-    - name: Build Executable
-      run: |
-        arch -${{ matrix.architecture }} nuitka \
-        --assume-yes-for-downloads \
-        --show-scons \
-        --clang \
-        --lto=no \
-        --jobs=4 \
-        --static-libpython=no \
-        --standalone \
-        --enable-plugin=anti-bloat \
-        --show-modules \
-        --show-anti-bloat-changes \
-        --follow-stdlib \
-        --follow-imports \
-        --enable-plugin=tk-inter \
-        --include-package=undetected_chromedriver \
-        --nofollow-import-to="*.tests" \
-        --nofollow-import-to="unittest" \
-        --nofollow-import-to="pydoc" \
-        --nofollow-import-to="test" \
-        --prefer-source-code \
-        --include-data-dir=".seleniumwire=.seleniumwire" \
-        --macos-target-arch=${{ matrix.architecture }} \
-        StreamLabsTikTokStreamKeyGenerator.py
+      - name: Build Executable
+        run: |
+          arch -${{ matrix.architecture }} nuitka \
+          --assume-yes-for-downloads \
+          --show-scons \
+          --clang \
+          --lto=no \
+          --jobs=4 \
+          --static-libpython=no \
+          --standalone \
+          --enable-plugin=anti-bloat \
+          --show-modules \
+          --show-anti-bloat-changes \
+          --follow-stdlib \
+          --follow-imports \
+          --enable-plugin=tk-inter \
+          --include-package=undetected_chromedriver \
+          --nofollow-import-to="*.tests" \
+          --nofollow-import-to="unittest" \
+          --nofollow-import-to="pydoc" \
+          --nofollow-import-to="test" \
+          --prefer-source-code \
+          --include-data-dir=".seleniumwire=.seleniumwire" \
+          --include-data-dir="seleniumwire=seleniumwire" \
+          --macos-target-arch=${{ matrix.architecture }} \
+          StreamLabsTikTokStreamKeyGenerator.py
 
-    - name: Compress Executable
-      run: |
-        zip -r StreamLabsTikTokStreamKeyGenerator-${{ matrix.architecture }}-macos.zip StreamLabsTikTokStreamKeyGenerator.dist/*
+      - name: Compress Executable
+        run: |
+          zip -r StreamLabsTikTokStreamKeyGenerator-${{ matrix.architecture }}-macos.zip StreamLabsTikTokStreamKeyGenerator.dist/*
 
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: macos-${{ matrix.architecture }}
-        path: |
-          StreamLabsTikTokStreamKeyGenerator-${{ matrix.architecture }}-macos.zip
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: macos-${{ matrix.architecture }}
+          path: |
+            StreamLabsTikTokStreamKeyGenerator-${{ matrix.architecture }}-macos.zip
 
   build_linux:
     runs-on: ubuntu-22.04
@@ -180,19 +183,18 @@ jobs:
         build_type: [Release]
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y ccache python3-pip python3-tk zip python3-distutils
+          python3 -m pip install --upgrade pip
+          pip3 install Nuitka clang
+          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
 
-    - name: Install dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y ccache python3-pip python3-tk zip python3-distutils
-        python3 -m pip install --upgrade pip
-        pip3 install Nuitka clang
-        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
-
-    - name: Build Executable
-      run: |
+      - name: Build Executable
+        run: |
           nuitka \
           --assume-yes-for-downloads \
           --show-scons \
@@ -214,18 +216,18 @@ jobs:
           --nofollow-import-to="test" \
           --prefer-source-code \
           --include-data-dir=".seleniumwire=.seleniumwire" \
+          --include-data-dir="seleniumwire=seleniumwire" \
           StreamLabsTikTokStreamKeyGenerator.py
 
+      - name: Compress Executable
+        run: zip -r StreamLabsTikTokStreamKeyGenerator-linux.zip StreamLabsTikTokStreamKeyGenerator.dist/*
 
-    - name: Compress Executable
-      run: zip -r StreamLabsTikTokStreamKeyGenerator-linux.zip StreamLabsTikTokStreamKeyGenerator.dist/*
-
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: linux-
-        path: |
-          ./StreamLabsTikTokStreamKeyGenerator-linux.zip
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: linux-
+          path: |
+            ./StreamLabsTikTokStreamKeyGenerator-linux.zip
 
   release:
     runs-on: ubuntu-latest
@@ -269,4 +271,3 @@ jobs:
             ./macos/StreamLabsTikTokStreamKeyGenerator-x86_64-macos.zip
             ./macos/StreamLabsTikTokStreamKeyGenerator-arm64-macos.zip
             ./linux/StreamLabsTikTokStreamKeyGenerator-linux.zip
-  
